name: Upload files

on:
  push:
    branches:
      - NS
  workflow_dispatch:

jobs:
  upload:
    name: Upload files via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.FTP_URL }}
          username: ${{ vars.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
